io:
  input_data_path: '/home/swim/data/BTO_01_crop.mat'
  result_dir: '/home/swim/Si_project/wrapper/results'
  verbosity: 1

ptycho:
  engine: 'fold_slice'
  path: '/home/swim/Si_project/lemon-ptychography/fold_slice'
  params:
    alpha_max: 30
    defocus: -200
    rot_ang: 1
    Nlayers: 20
    thickness: 250
    voltage: 200
    rbf: 37
    Nprobe: 1
    N_scan_x: 64
    N_scan_y: 64
    tilt_x: 2
    tilt_y: 0 
    scan_step_size: 0.36
    Niter: 20
    Niter_save_results: 10
    CBED_size: 192
    ADU: 1
    extra_print_info: 'FIB'
    scan_number: 1
    gpu_id: 1
    roi_label: '0_Ndp64'
    diff_pattern_blur: 1
    probe_change_start: 1
    object_change_start: 1
    grouping: 128
    probe_posiiton_search: 1
    regularize_layers: 0.1
    variable_probe: 'false'

bo:
  parallel_jobs: 4
  algorithm: ucb
  params:
    alpha_max:
    defocus: 150
    rot_ang: 1
    Nlayers:
    thickness: 150
