job:
  type: "random+sobo"
  random_iters: 16
  sobo_iters: 512

io:
  input_data_path: '/home/swim/shared/Si_project/data/Si30V3_2.mat'
  result_dir: '/home/swim/bo-ptycho/results/Si30V3_2/260816'
  verbosity: 1

ptycho:
  engine: 'fold_slice'
  path: '/home/swim/fold_slice-park'
  params:
    voltage: 200
    alpha_max: 30
    defocus: 200
    rot_ang: 0.1
    Nlayers: 30
    thickness: 650
    rbf: 38
    tilt_x: 5
    tilt_y: 3 
    scan_step_size: 0.35

    Niter: 100
    Niter_save_results: 100

    CBED_size: 192
    ADU: 1
    Nprobe: 1
    N_scan_x: 64
    N_scan_y: 64 
    extra_print_info: 'FIB'
    scan_number: 1
    gpu_id: 1
    roi_label: '0_Ndp64'
    diff_pattern_blur: 1
    probe_change_start: 1
    object_change_start: 1
    grouping: 64
    probe_position_search: 1
    regularize_layers: 0.2
    variable_probe: false

bo:
  batch: 4
  acquisition: 'ucb'
  beta: 0.1
  metric: 'log_fourier'
  params:
    alpha_max:
    defocus:
      radius: 100
    rot_ang:
    Nlayers:
      radius: 5
      type: int
    thickness:
      radius: 150
  train_x:
  train_y:
